#!/bin/sh
# Git post-checkout hook - updates submodules after checkout
#
# This hook runs after:
#   - git checkout
#   - git switch
#   - git clone (with checkout)
#
# Arguments:
#   $1 - ref of previous HEAD
#   $2 - ref of new HEAD
#   $3 - flag (1 = branch checkout, 0 = file checkout)

# Only run on branch checkouts, not file checkouts
if [ "$3" = "0" ]; then
    exit 0
fi

echo "Updating submodules..."
git submodule update --init --recursive --remote

exit 0
