# Documentation
"kind/documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

# CI/CD
"area/ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

# Configuration
"area/config":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.toml"
          - "**/*.yaml"
          - "**/*.yml"
          - "!.github/**/*"

# Dependencies
"area/deps":
  - changed-files:
      - any-glob-to-any-file:
          - "**/Cargo.toml"
          - "**/Cargo.lock"

# Testing
"area/testing":
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**/*"
          - "**/*_test.rs"
          - "**/*_tests.rs"
          - "src/testing/**/*"

# Client
"area/client":
  - changed-files:
      - any-glob-to-any-file:
          - "src/client/**/*"
          - "src/client.rs"
          - "src/vault/**/*"

# Protocol buffers and gRPC
"area/proto":
  - changed-files:
      - any-glob-to-any-file:
          - "src/transport/**/*"
          - "proto/**/*"
          - "build.rs"

# Authentication
"area/auth":
  - changed-files:
      - any-glob-to-any-file:
          - "src/auth/**/*"
          - "src/credentials/**/*"

# API
"area/api":
  - changed-files:
      - any-glob-to-any-file:
          - "src/api/**/*"
          - "src/check/**/*"
          - "src/relationships/**/*"
          - "src/expand/**/*"
          - "src/control/**/*"

# Data models and types
"area/models":
  - changed-files:
      - any-glob-to-any-file:
          - "src/types/**/*"
          - "src/models/**/*"
          - "src/error/**/*"

# Derive macros
"area/derive":
  - changed-files:
      - any-glob-to-any-file:
          - "inferadb-derive/**/*"

# Examples
"area/examples":
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**/*"
